[package]
name = "fractional_index"
version = "0.1.0"
edition = "2018"
readme = "README.md"
description = "An implementation of fractional indexing."
authors = ["Paul Butler <paulgb@gmail.com>"]
license = "MIT"

[dependencies]
serde = { version = "1.0.130", features = ["derive"], optional=true }

[build-dependencies]
skeptic = "0.13"

[dev-dependencies]
skeptic = "0.13"

[features]
default = ["serde"]