[package]
name = "fractional_index"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.130", features = ["derive"], optional=true }

[build-dependencies]
skeptic = "0.13"

[dev-dependencies]
skeptic = "0.13"

[features]
default = ["serde"]